# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Disabling ARP checking
noarp

# Disabling link state monitoring
nolink

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name, wpad_url
option classless_static_routes
option interface_mtu

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Disable IPv6 router solicitation
noipv6rs
